### ISSUE TITLE
http-full-proxy calls succeed via curl but fail in browser and postman

### ISSUE THREAD

**Issue by dmrolfs** [actix/examples#142] opened 2019-06-14 04:02 UTC
playing the the actix-examples/http-full-proxy against httpbin.org (offers lots of REST options to proxy):
`cargo run 127.0.0.1 8080 httpbin.org 80`
hitting the proxy via curl works: `curl -S -v http://127.0.0.1:8080/get`
But the same call via Postman (or firefox browser) fails with a page

> Could not get any response
> There was an error connecting to 127.0.0.1:8080/get.
> Why this might have happened:
> The server couldn't send a response:
> Ensure that the backend is working properly
> Self-signed SSL certificates are being blocked:
> Fix this by turning off 'SSL certificate verification' in Settings > General
> Proxy configured incorrectly
> Ensure that proxy is configured correctly in Settings > Proxy
> Request timeout:
> Change request timeout in Settings > General

I confirmed that postman timeout was set to infinite. Also in postman I disabled certificate verification. 

I played with filtering the response header values and found that it only works once I filter out both the content-encoding and content-length headers. I appreciate any guidance on what I should look at to fix. Thanks
(Obviously I pulled the example from another call in postman… 127.0.0.1:8080/get presents the same way as uuid)

**Comment by arve0** [comment] 2019-06-15 23:53
I had the same problem. `content-encoding` is probably because client decompresses bytes before streaming them, and should be omitted. Not sure about `content-length`, but omitting the header works.

**Comment by dmrolfs** [comment] 2019-06-24 21:34
@arve0 regarding `content-encoding`: if I let the response body flow back to the original caller without touching it, can I also propagate the `content-encoding` header? Seems like it should work, but it does not. What am I missing?

re `content-length`: I thought about trying to recalculate the `content-length` value, but hoping actix-web would handle that in forming the response back to the caller? Is there a way to force that via the actix-web API?

I'm happy to pursue an experiment with ideas and to submit possible fixes back, and any guidance is appreciated! Thanks

**Comment by arve0** [comment] 2019-06-25 05:21
> Seems like it should work, but it does not. What am I missing?

Depends on what the client stream is. Is it the encoded byte-stream, e.g. gzip, or is it decompressed bytes? See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding

> I thought about trying to recalculate the content-length

You cannot calculate `content-length` before actually knowing it. `content-length` is sent before the body is sent, so that is impossible when streaming. The origin server here typically knows the `content-length` because it is reading a file from the disk.

**Comment by fafhrd91** [comment] 2019-06-25 07:46
client decompression could be disabled with [ClientRequest::no_decompress()](https://docs.rs/awc/0.2.1/awc/struct.ClientRequest.html#method.no_decompress) method

**Comment by fafhrd91** [comment] 2019-06-28 08:52
should be fixed by #151

**Closed by fafhrd91** 2019-06-28 08:52 UTC

**Comment by arve0** [comment] 2019-06-28 16:57
#151 does not fix "`content-length`-issue".

**Comment by arve0** [comment] 2019-06-28 17:19
Also reproduced with [wrk](https://github.com/wg/wrk):

```sh
cd http-full-proxy
cargo run 0.0.0.0 8080 httpbin.org 80
# new terminal window
wrk -d 1s http://localhost:8080/get
```

output:
```
Running 1s test @ http://localhost:8080/get
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.00us    0.00us   0.00us     nan%
    Req/Sec     0.00      0.00     0.00       nan%
  0 requests in 1.02s, 0.00B read
  Socket errors: connect 0, read 28, write 0, timeout 0
Requests/sec:      0.00
Transfer/sec:       0.00B
```

expected output:
```
Running 1s test @ http://localhost:8080/get
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   323.95ms   38.97ms 381.58ms   46.67%
    Req/Sec    17.12     11.42    39.00     62.50%
  30 requests in 1.02s, 16.76KB read
Requests/sec:     29.37
Transfer/sec:     16.41KB
```
