### ISSUE TITLE
websocket chat example doesn't compile with newest versions

### ISSUE THREAD

**Issue by rokit** [actix/examples#440] opened 2021-07-25 04:04 UTC
Going from Actix 0.10 to 0.12.0 seems to be the problem. Here is the error I'm getting for the [chat example](https://github.com/actix/examples/tree/master/websockets/chat):
```
error[E0277]: the trait bound `WsChatSession: actix::actor::Actor` is not satisfied
   --> src\main.rs:59:5
    |
59  |     type Context = ws::WebsocketContext<Self>;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `actix::actor::Actor` is not implemented for `WsChatSession`
```

![image](https://user-images.githubusercontent.com/1229742/126887249-0b99cae2-9922-433e-b39b-c1d4341aee28.png)

And here are the versions I'm using:
```
[dependencies]
actix = "0.12.0"
actix-web = "3.3.2"
actix-web-actors = "3.0.0"
actix-files = "0.5.0"
rand = "0.8.4"
env_logger = "0.9.0"
```

**Comment by sahina** [comment] 2021-08-11 15:34
i am working on this

**Comment by AdriaanPrinsloo** [comment] 2022-01-20 10:22
@sahina any progress here?  I'm having similar issues with upgrading actix.

**Comment by robjtede** [comment] 2022-01-20 12:29
duplicate of https://github.com/actix/examples/issues/443

**Closed by robjtede** 2022-01-20 12:29 UTC
